@URL = {{BASE_URL}}/storage/upload/chats/01KJD0TXF53RBZJ4R3QK431AKN/messages/01KJECM4CT4VR8TCXGZAHTVH68/attachments


### Generate upload URLs for attachments
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "files_names": [
    "image.jpg",
    "image.png"
  ]
}