services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: equiny
      POSTGRES_USER: equiny
      POSTGRES_PASSWORD: equiny
    ports:
      - "5432:5432"
    volumes:
      - equiny_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U equiny -d equiny"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  equiny_postgres_data:
