"""add bio and phone attrivutes  to owner model

Revision ID: 048d3bde9139
Revises: c7a8bdaa086f
Create Date: 2026-02-16 19:21:17.720884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048d3bde9139'
down_revision: Union[str, None] = 'c7a8bdaa086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'phone')
    op.drop_column('owners', 'bio')
    # ### end Alembic commands ###
