"""remove owner_id atribute from horse model

Revision ID: 0a28607fd86a
Revises: ba60e01cdcb1
Create Date: 2026-02-10 20:12:54.761672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a28607fd86a'
down_revision: Union[str, None] = 'ba60e01cdcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
