"""add_matching_swipes_and_matches_tables

Revision ID: 1980133d6f77
Revises: 048d3bde9139
Create Date: 2026-02-17 10:48:49.178352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1980133d6f77'
down_revision: Union[str, None] = '048d3bde9139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('horse_a_id', sa.String(), nullable=False),
    sa.Column('horse_b_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_a_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['horse_b_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_horse_a_id'), 'matches', ['horse_a_id'], unique=False)
    op.create_index(op.f('ix_matches_horse_b_id'), 'matches', ['horse_b_id'], unique=False)
    op.create_index('ix_matches_pair', 'matches', ['horse_a_id', 'horse_b_id'], unique=True)
    op.create_table('swipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_horse_id', sa.String(), nullable=False),
    sa.Column('to_horse_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['to_horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_horse_id', 'to_horse_id', name='uq_swipe_pair')
    )
    op.create_index(op.f('ix_swipes_from_horse_id'), 'swipes', ['from_horse_id'], unique=False)
    op.create_index(op.f('ix_swipes_to_horse_id'), 'swipes', ['to_horse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipes_to_horse_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_from_horse_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index('ix_matches_pair', table_name='matches')
    op.drop_index(op.f('ix_matches_horse_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_horse_a_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
