"""add avatar attributes to owner model

Revision ID: 20260218_144708
Revises: 1980133d6f77
Create Date: 2026-02-18 14:47:08

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260218_144708'
down_revision: Union[str, None] = '1980133d6f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('avatar_key', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('avatar_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'avatar_name')
    op.drop_column('owners', 'avatar_key')
    # ### end Alembic commands ###
