"""add_horse_images_table

Revision ID: 48a95422cca7
Revises: 5bb89e02f8eb
Create Date: 2026-02-15 15:09:37.775390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a95422cca7'
down_revision: Union[str, None] = '5bb89e02f8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('horse_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_images_horse_id'), 'horse_images', ['horse_id'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_horse_images_horse_id'), table_name='horse_images')
    op.drop_table('horse_images')
    # ### end Alembic commands ###
