"""add viewed columns to matches

Revision ID: 59d7e8278a60
Revises: 20260218_144708
Create Date: 2026-02-18 14:54:05.157398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d7e8278a60'
down_revision: Union[str, None] = '20260218_144708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('has_horse_a_viewed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('matches', sa.Column('has_horse_b_viewed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'has_horse_b_viewed')
    op.drop_column('matches', 'has_horse_a_viewed')
    # ### end Alembic commands ###
