"""add has completed onboarding to owner model

Revision ID: 5ddbeb7a8087
Revises: c3d9f2a14b7e
Create Date: 2026-02-16 07:53:18.444227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddbeb7a8087'
down_revision: Union[str, None] = 'c3d9f2a14b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
