"""add has completed onboarding to owner model

Revision ID: 61df63cbfb44
Revises: 5ddbeb7a8087
Create Date: 2026-02-16 07:59:12.233269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61df63cbfb44'
down_revision: Union[str, None] = '5ddbeb7a8087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'has_completed_onboarding')
    # ### end Alembic commands ###
