"""add relation between horser model and owner model

Revision ID: 8eb376d301fe
Revises: 48a95422cca7
Create Date: 2026-02-15 15:50:48.152818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb376d301fe'
down_revision: Union[str, None] = '48a95422cca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'horses', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horses', type_='foreignkey')
    op.drop_column('horses', 'owner_id')
    # ### end Alembic commands ###
