"""add_chats_table

Revision ID: a6e4632d5521
Revises: 59d7e8278a60
Create Date: 2026-02-19 14:36:51.893657

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e4632d5521'
down_revision: str | None = '59d7e8278a60'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_a_id', sa.String(), nullable=False),
    sa.Column('owner_b_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_a_id'], ['owners.id'] ),
    sa.ForeignKeyConstraint(['owner_b_id'], ['owners.id'] ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_owner_a_id'), 'chats', ['owner_a_id'], unique=False)
    op.create_index(op.f('ix_chats_owner_b_id'), 'chats', ['owner_b_id'], unique=False)
    op.create_index('ix_chats_owners_pair', 'chats', ['owner_a_id', 'owner_b_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_owners_pair', table_name='chats')
    op.drop_index(op.f('ix_chats_owner_b_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_owner_a_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
