"""add description attributee to horse model

Revision ID: c7a8bdaa086f
Revises: 7c8d9e10f2a3
Create Date: 2026-02-16 18:24:39.851172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a8bdaa086f'
down_revision: Union[str, None] = '7c8d9e10f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'description')
    # ### end Alembic commands ###
