"""add horse location coordinates columns

Revision ID: f757cf81ecd2
Revises: 20260301_000000
Create Date: 2026-03-12 17:02:14.833981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f757cf81ecd2'
down_revision: Union[str, None] = '20260301_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'horses',
        sa.Column(
            'location_latitude', sa.Float(), nullable=False, server_default=sa.text('0')
        ),
    )
    op.add_column(
        'horses',
        sa.Column(
            'location_longitude',
            sa.Float(),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.alter_column('horses', 'location_latitude', server_default=None)
    op.alter_column('horses', 'location_longitude', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'location_longitude')
    op.drop_column('horses', 'location_latitude')
    # ### end Alembic commands ###
