@URL = http://localhost:8080/auth
@EMAIL = user@example.com
@PASSWORD = changeme123
@OWNER_NAME = Owner Example

### Sign In
POST {{URL}}/sign-in
Content-Type: application/json

{
  "account_email": "{{EMAIL}}",
  "account_password": "{{PASSWORD}}"
}


### Sign Up
POST {{URL}}/sign-up
Content-Type: application/json

{
  "owner_name": "{{OWNER_NAME}}",
  "account_email": "{{EMAIL}}",
  "account_password": "{{PASSWORD}}"
}
