@URL = http://localhost:8080/profiling/horses
@HORSE_ID = 01KHPD158QDMXWTGENWZK5DFYD

### Create Horse
POST {{URL}}
Content-Type: application/json

{
  "name": "Mr. Cavalo",
  "birth_month": 1,
  "birth_year": 2018,
  "breed": "quarto de milha",
  "sex": "male",
  "location": {
    "state": "SP",
    "city": "São Paulo"
  }
}

### Get Horse
GET {{URL}}/{{HORSE_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Update Horse
PUT {{URL}}/{{HORSE_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "Mr. Cavalo",
  "birth_month": 1,
  "birth_year": 2018,
  "height": 1.5,
  "breed": "quarto de milha",
  "sex": "male",
  "location": {
    "state": "SP",
    "city": "São Paulo"
  }
}

### Get Horse Gallery
GET {{URL}}/{{HORSE_ID}}/gallery
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Update Horse Gallery
PUT {{URL}}/{{HORSE_ID}}/gallery
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "images": [
    {
      "key": "123e4567-e89b-12d3-a456-426614174000",
      "name": "image.jpg"
    }
  ]
}

### Get Horse Feed
GET {{URL}}/{{HORSE_ID}}/feed
?sex=female
&min_age=1
&max_age=30
&height=2
&city=Bagé
&state=RS
&limit=10
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Get Horse Matches
GET {{URL}}/{{HORSE_ID}}/matches
Content-Type: application/json
Authorization: Bearer {{JWT}}

### View Horse Match
GET {{URL}}/{{HORSE_ID}}/matches/01KHPDT8C9BM21QXZPT8QF2QYT
Content-Type: application/json
Authorization: Bearer {{JWT}}

