@URL = {{BASE_URL}}/matching/matches


### Dismatch Horse
DELETE {{URL}}?horse_a_id=01KHPD158QDMXWTGENWZK5DFYD&horse_b_id=01KHPDVN4W6Z2Y7X8C3V9B1N0M
Content-Type: application/json
Authorization: Bearer {{JWT}}

