@URL = {{BASE_URL}}/matching/swipes

POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "from_horse_id": "01KHPD158QDMXWTGENWZK5DFYD",
  "to_horse_id": "01KHPDT8C9BM21QXZPT8QF2QYT",
  "decision": "like"
}

