from typing import Optional

class PostgresContainer:
    def __init__(self, image: str = 'postgres:latest', **kwargs: object) -> None: ...
    def get_connection_url(
        self, host: Optional[str] = None, driver: Optional[str] = None
    ) -> str: ...
    def __enter__(self) -> 'PostgresContainer': ...
    def __exit__(self, *args: object) -> None: ...
